/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

export const convertFieldToBytes = (len: number, num: bigint): Uint8Array => {
  const arr = new Uint8Array(len);
  let n = num;
  for (let i = len - 1; i >= 0; i--) {
    arr[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  return arr;
};
